[project]
name = "rudra-g-23-github-io"
version = "0.1.0"
description = "My profile for Public"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "dotenv>=0.9.9",
    "fastapi>=0.136.1",
    "groq>=1.2.0",
    "numpy>=2.4.4",
    "pydantic>=2.13.3",
    "requests>=2.33.1",
    "rich>=15.0.0",
    "ruff>=0.15.16",
    "sentence-transformers>=5.4.1",
    "torch>=2.11.0",
    "transformers>=5.7.0",
    "uvicorn>=0.46.0",
]
